Fact branch
Patibandha/PD008bootcamp pull request #15
Opened 2021-07-13 22:13 UTC by Shailja2606

adding programs with class function

2021-07-15 22:30 UTC, Shailja2606 commented
updated factorial and palindrom program with class

2021-07-21 23:32 UTC, Patibandha requested changes
made changes

2021-07-21 23:32 UTC, Patibandha commented on shailja_work/calculator_class.py
> +obj_cal = Calculator()
need to call object of class inside if your main() method line #20

2021-07-21 23:32 UTC, Patibandha commented on shailja_work/factorial_class.py
> +obj_fac = Fact()
same mistake it suppose to from your main() function line #20

2021-07-21 23:32 UTC, Patibandha commented on shailja_work/palindrom_class.py
> +obj_pali = Pali()
this is wrong!

2021-07-21 23:32 UTC, Patibandha commented on shailja_work/test_calculator_class.py
> +
it suppose to be -ve test cases

2021-07-21 23:32 UTC, Patibandha commented on shailja_work/test_factorial_class.py
> +
more -ve test cases needed

2021-07-21 23:32 UTC, Patibandha commented on shailja_work/test_palindrome_class.py
> +    LOGGER.warning("The string is a palindrome")
what about assert false

2021-08-06 23:54 UTC, merged